## Dataframe basics:

In [ ]:
import pandas as pd
details = {
    "name": ["raja", "Dhairya", "Raj"],
    "age": [12, 14, 15],
    "classes": [8, 9, 10],
}

details_person=pd.DataFrame(details , index :['a','b','c'])
print(details_person)

      name  age  classes
0     raja   12        8
1  Dhairya   14        9
2      Raj   15       10

In [ ]:
details_person.head(1)# this shows only (x) x number of rows

      name  age  classes
0     raja   12        8
1  Dhairya   14        9
2      Raj   15       10

In [ ]:
details_person.tail() #this shows last row in an element

      name  age  classes
0     raja   12        8
1  Dhairya   14        9
2      Raj   15       10

In [9]:
details_person.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      str
 1   age      3 non-null      int64
 2   classes  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [11]:
details_person.shape

(3, 3)

In [13]:
details_person.columns

Index(['name', 'age', 'classes'], dtype='str')

In [15]:
details_person.describe()

             age  classes
count   3.000000      3.0
mean   13.666667      9.0
std     1.527525      1.0
min    12.000000      8.0
25%    13.000000      8.5
50%    14.000000      9.0
75%    14.500000      9.5
max    15.000000     10.0

In [20]:
details_person.rename(columns ={ 'classes':'class'},inplace =True)#if inplace not used then only when ran command only then the name is changed 
print(details_person)

      name  age  class
0     raja   12      8
1  Dhairya   14      9
2      Raj   15     10