## Coloumns Selection

In [ ]:
import pandas as pd

details = {
    "name": ["raja", "Dhairya", "Raj"],
    "age": [12, 14, 15],
    "classes": [8, 9, 10],
}
details_dataframe = pd.DataFrame(details)
print(details_dataframe)

In [5]:
details_dataframe[["name"]]#single coloumn selection 
details_dataframe[["name", "classes"]]#Multiple coloumn selection

      name  classes
0     raja        8
1  Dhairya        9
2      Raj       10

In [11]:
# row selection
# loc  : label based indexing
details_dataframe.loc[
    (details_dataframe.name == "Dhairya") & (details_dataframe.classes > 5)
]
# used condition if the same person has is in the list


# code is made case sensitive to keep the practice safe and memorable

      name  age  classes
1  Dhairya   14        9

In [14]:
#iloc : index label based indexing 
details_dataframe.iloc[0]

details_dataframe.loc[0:2]

      name  age  classes
0     raja   12        8
1  Dhairya   14        9
2      Raj   15       10

In [16]:
details_dataframe.iloc[0:2]

      name  age  classes
0     raja   12        8
1  Dhairya   14        9