## Pandas

In [2]:
import pandas as pd 
import numpy as np

### DataFrame

In [29]:
# dataframe : it is the tabular representation of the data

basic = pd.DataFrame([1, 2, 3, 4, 5], index=["a", "b", "c", "d", "e"], columns=["ok"])
print(basic)

details = {
    "name": ["raja", "Dhairya", "Raj"],
    "age": [12, 14, 15],
    "classes": [8, 9, 10],
}
details_dataframe =pd.DataFrame(details)
print(pd.DataFrame(details))

   ok
a   1
b   2
c   3
d   4
e   5
      name  age  classes
0     raja   12        8
1  Dhairya   14        9
2      Raj   15       10

In [ ]:
details_dataframe.head(1)#(x) i.e. x rows of the chart from begining

  name  age  classes
2  Raj   15       10

In [ ]:
details_dataframe.tail(1)#(x) i.e. x rows of the chart ending

  name  age  classes
2  Raj   15       10